run:
  concurrency: 4
  timeout: 5m
  skip-dirs-use-default: true
  modules-download-mode: readonly
  allow-parallel-runners: false
  skip-dirs:
    - "simulation_runbooks"
    - "cmd"
linters:
  # commented linters are intended to be uncommented, but currently have a lot
  # of errors. these can be enabled one at a time.
  enable:
    - bodyclose
    - exhaustive
    # - forcetypeassert
    # - funlen
    - goconst
    # - gocognit
    - gocyclo
    - gofmt
    - goimports
    # - gomnd
    # - gosec
    - importas
    - interfacebloat
    # - ireturn
    - makezero
    # - misspell
    - nestif
    # - nlreturn
    # - prealloc
    # - unconvert
    # - unparam
    - usestdlibvars
    # - whitespace
    # - wsl