// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	store "github.com/smartcontractkit/ocr2keepers/pkg/v3/store"
	mock "github.com/stretchr/testify/mock"
)

// MockMetadataStore is an autogenerated mock type for the MetadataStore type
type MockMetadataStore struct {
	mock.Mock
}

// Set provides a mock function with given fields: _a0, _a1
func (_m *MockMetadataStore) Set(_a0 store.MetadataKey, _a1 interface{}) {
	_m.Called(_a0, _a1)
}

// NewMockMetadataStore creates a new instance of MockMetadataStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataStore {
	mock := &MockMetadataStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
