// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	ocr2keepers "github.com/smartcontractkit/ocr2keepers/pkg"
)

// MockPreProcessor is an autogenerated mock type for the PreProcessor type
type MockPreProcessor struct {
	mock.Mock
}

// PreProcess provides a mock function with given fields: _a0, _a1
func (_m *MockPreProcessor) PreProcess(_a0 context.Context, _a1 []ocr2keepers.UpkeepPayload) ([]ocr2keepers.UpkeepPayload, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []ocr2keepers.UpkeepPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []ocr2keepers.UpkeepPayload) ([]ocr2keepers.UpkeepPayload, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []ocr2keepers.UpkeepPayload) []ocr2keepers.UpkeepPayload); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ocr2keepers.UpkeepPayload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []ocr2keepers.UpkeepPayload) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPreProcessor creates a new instance of MockPreProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPreProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPreProcessor {
	mock := &MockPreProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
