// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockRatio is an autogenerated mock type for the Ratio type
type MockRatio struct {
	mock.Mock
}

// OfInt provides a mock function with given fields: _a0
func (_m *MockRatio) OfInt(_a0 int) int {
	ret := _m.Called(_a0)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewMockRatio interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRatio creates a new instance of MockRatio. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRatio(t mockConstructorTestingTNewMockRatio) *MockRatio {
	mock := &MockRatio{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
