// Code generated by mockery v2.32.2. DO NOT EDIT.

package mocks

import (
	ocr2keepers "github.com/smartcontractkit/ocr2keepers/pkg"
	mock "github.com/stretchr/testify/mock"
)

// MockRecoverableProvider is an autogenerated mock type for the RecoverableProvider type
type MockRecoverableProvider struct {
	mock.Mock
}

// GetRecoverables provides a mock function with given fields:
func (_m *MockRecoverableProvider) GetRecoverables() ([]ocr2keepers.UpkeepPayload, error) {
	ret := _m.Called()

	var r0 []ocr2keepers.UpkeepPayload
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]ocr2keepers.UpkeepPayload, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []ocr2keepers.UpkeepPayload); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ocr2keepers.UpkeepPayload)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRecoverableProvider creates a new instance of MockRecoverableProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecoverableProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecoverableProvider {
	mock := &MockRecoverableProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
