// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	ocr2keepers "github.com/smartcontractkit/ocr2keepers/pkg"
	mock "github.com/stretchr/testify/mock"
)

// MockResultStore is an autogenerated mock type for the ResultStore type
type MockResultStore struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *MockResultStore) Add(_a0 ...ocr2keepers.CheckResult) {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

type mockConstructorTestingTNewMockResultStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockResultStore creates a new instance of MockResultStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockResultStore(t mockConstructorTestingTNewMockResultStore) *MockResultStore {
	mock := &MockResultStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
