// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	types "github.com/smartcontractkit/ocr2keepers/pkg/v3/types"
	mock "github.com/stretchr/testify/mock"
)

// Encoder is an autogenerated mock type for the Encoder type
type Encoder struct {
	mock.Mock
}

// After provides a mock function with given fields: _a0, _a1
func (_m *Encoder) After(_a0 types.BlockNumber, _a1 types.BlockNumber) (bool, error) {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(types.BlockNumber, types.BlockNumber) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(types.BlockNumber, types.BlockNumber) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(types.BlockNumber, types.BlockNumber) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Increment provides a mock function with given fields: _a0
func (_m *Encoder) Increment(_a0 types.BlockNumber) (types.BlockNumber, error) {
	ret := _m.Called(_a0)

	var r0 types.BlockNumber
	var r1 error
	if rf, ok := ret.Get(0).(func(types.BlockNumber) (types.BlockNumber, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(types.BlockNumber) types.BlockNumber); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.BlockNumber)
	}

	if rf, ok := ret.Get(1).(func(types.BlockNumber) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewEncoder interface {
	mock.TestingT
	Cleanup(func())
}

// NewEncoder creates a new instance of Encoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEncoder(t mockConstructorTestingTNewEncoder) *Encoder {
	mock := &Encoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
