// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/smartcontractkit/chainlink-automation/pkg/v3/types"
	mock "github.com/stretchr/testify/mock"
)

// MockMetadataStore is an autogenerated mock type for the MetadataStore type
type MockMetadataStore struct {
	mock.Mock
}

// AddProposals provides a mock function with given fields: proposals
func (_m *MockMetadataStore) AddProposals(proposals ...types.CoordinatedBlockProposal) {
	_va := make([]interface{}, len(proposals))
	for _i := range proposals {
		_va[_i] = proposals[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Close provides a mock function with given fields:
func (_m *MockMetadataStore) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBlockHistory provides a mock function with given fields:
func (_m *MockMetadataStore) GetBlockHistory() types.BlockHistory {
	ret := _m.Called()

	var r0 types.BlockHistory
	if rf, ok := ret.Get(0).(func() types.BlockHistory); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.BlockHistory)
		}
	}

	return r0
}

// RemoveProposals provides a mock function with given fields: proposals
func (_m *MockMetadataStore) RemoveProposals(proposals ...types.CoordinatedBlockProposal) {
	_va := make([]interface{}, len(proposals))
	for _i := range proposals {
		_va[_i] = proposals[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// SetBlockHistory provides a mock function with given fields: _a0
func (_m *MockMetadataStore) SetBlockHistory(_a0 types.BlockHistory) {
	_m.Called(_a0)
}

// Start provides a mock function with given fields: _a0
func (_m *MockMetadataStore) Start(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ViewProposals provides a mock function with given fields: utype
func (_m *MockMetadataStore) ViewProposals(utype types.UpkeepType) []types.CoordinatedBlockProposal {
	ret := _m.Called(utype)

	var r0 []types.CoordinatedBlockProposal
	if rf, ok := ret.Get(0).(func(types.UpkeepType) []types.CoordinatedBlockProposal); ok {
		r0 = rf(utype)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.CoordinatedBlockProposal)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockMetadataStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMetadataStore creates a new instance of MockMetadataStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMetadataStore(t mockConstructorTestingTNewMockMetadataStore) *MockMetadataStore {
	mock := &MockMetadataStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
