// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/smartcontractkit/ocr2keepers/pkg/v3/types"
	mock "github.com/stretchr/testify/mock"
)

// MockMetadataStore is an autogenerated mock type for the MetadataStore type
type MockMetadataStore struct {
	mock.Mock
}

// AddConditionalProposal provides a mock function with given fields: _a0
func (_m *MockMetadataStore) AddConditionalProposal(_a0 ...types.CoordinatedProposal) {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// AddLogRecoveryProposal provides a mock function with given fields: _a0
func (_m *MockMetadataStore) AddLogRecoveryProposal(_a0 ...types.CoordinatedProposal) {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Close provides a mock function with given fields:
func (_m *MockMetadataStore) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBlockHistory provides a mock function with given fields:
func (_m *MockMetadataStore) GetBlockHistory() types.BlockHistory {
	ret := _m.Called()

	var r0 types.BlockHistory
	if rf, ok := ret.Get(0).(func() types.BlockHistory); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.BlockHistory)
		}
	}

	return r0
}

// RemoveConditionalProposal provides a mock function with given fields: _a0
func (_m *MockMetadataStore) RemoveConditionalProposal(_a0 ...types.CoordinatedProposal) {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// RemoveLogRecoveryProposal provides a mock function with given fields: _a0
func (_m *MockMetadataStore) RemoveLogRecoveryProposal(_a0 ...types.CoordinatedProposal) {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// SetBlockHistory provides a mock function with given fields: _a0
func (_m *MockMetadataStore) SetBlockHistory(_a0 types.BlockHistory) {
	_m.Called(_a0)
}

// Start provides a mock function with given fields: _a0
func (_m *MockMetadataStore) Start(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ViewConditionalProposal provides a mock function with given fields:
func (_m *MockMetadataStore) ViewConditionalProposal() []types.CoordinatedProposal {
	ret := _m.Called()

	var r0 []types.CoordinatedProposal
	if rf, ok := ret.Get(0).(func() []types.CoordinatedProposal); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.CoordinatedProposal)
		}
	}

	return r0
}

// ViewLogRecoveryProposal provides a mock function with given fields:
func (_m *MockMetadataStore) ViewLogRecoveryProposal() []types.CoordinatedProposal {
	ret := _m.Called()

	var r0 []types.CoordinatedProposal
	if rf, ok := ret.Get(0).(func() []types.CoordinatedProposal); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.CoordinatedProposal)
		}
	}

	return r0
}

// ViewProposals provides a mock function with given fields: utype
func (_m *MockMetadataStore) ViewProposals(utype types.UpkeepType) []types.CoordinatedProposal {
	ret := _m.Called(utype)

	var r0 []types.CoordinatedProposal
	if rf, ok := ret.Get(0).(func(types.UpkeepType) []types.CoordinatedProposal); ok {
		r0 = rf(utype)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.CoordinatedProposal)
		}
	}

	return r0
}

type mockConstructorTestingTNewMockMetadataStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockMetadataStore creates a new instance of MockMetadataStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockMetadataStore(t mockConstructorTestingTNewMockMetadataStore) *MockMetadataStore {
	mock := &MockMetadataStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
